/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    CardStackCard: typeof import('./src/components/CardStackCard.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    Contact: typeof import('./src/components/ContactPage.vue')['default']
    ContactPage: typeof import('./src/components/ContactPage.vue')['default']
    copy: typeof import('./src/components/WheelScrolling copy.vue')['default']
    Fashion: typeof import('./src/components/FashionTable.vue')['default']
    FashionTable: typeof import('./src/components/FashionTable.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    ParallaxScroll: typeof import('./src/components/ParallaxScroll.vue')['default']
    PhoneMusic: typeof import('./src/components/PhoneMusic.vue')['default']
    PreviewCard: typeof import('./src/components/PreviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/PhoneMusic.vue')['default']
    Tets: typeof import('./src/components/tets.vue')['default']
    WheelScrolling: typeof import('./src/components/WheelScrolling.vue')['default']
  }
}
