/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    Home: typeof import('./src/components/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    ParallaxScroll: typeof import('./src/components/ParallaxScroll.vue')['default']
    PreviewCard: typeof import('./src/components/PreviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tets: typeof import('./src/components/tets.vue')['default']
    WheelScrolling: typeof import('./src/components/WheelScrolling.vue')['default']
  }
}
